services:
  db:
    image: postgres:17-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 953810aa-684f-11f0-b390-5ee52574761b
      POSTGRES_DB: agentdb