"""Add agent_type enum column

Revision ID: e086d98894e8
Revises: 60e4b334f2c0
Create Date: 2025-07-24 10:00:58.282586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e086d98894e8'
down_revision: Union[str, Sequence[str], None] = '60e4b334f2c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    agent_type_enum = sa.Enum('search_agent', name='agent_type_enum')
    agent_type_enum.create(op.get_bind())
    
    # Then add the column
    op.add_column('agent_configuration', sa.Column('agent_type', agent_type_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the column first
    op.drop_column('agent_configuration', 'agent_type')
    
    # Then drop the enum type
    agent_type_enum = sa.Enum('search_agent', name='agent_type_enum')
    agent_type_enum.drop(op.get_bind())
    # ### end Alembic commands ###
