"""Init migration

Revision ID: f8fe86eb25b8
Revises: 
Create Date: 2025-07-26 07:58:50.494117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8fe86eb25b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_configuration',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.Enum('search_agent', name='agent_type_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_execution',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('state', sa.Enum('pending', 'completed', 'failed', name='agent_execution_state'), nullable=False),
    sa.Column('executions', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('config_id', sa.UUID(), nullable=True),
    sa.Column('success_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['agent_configuration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_execution')
    op.drop_table('agent_configuration')
    # ### end Alembic commands ###
